[build]
  base = "city-side-ventures"
  publish = "city-side-ventures/dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"
# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200