funds:
  - name: Blue Venture
    color: blue
    market: Venture Capital Fund, Series A - C
    intro: Blue Venture is a Michigan-based Venture Capital Fund that was established to invest in fast growing, scalable, and post-revenue tech companies located in the US and North America. Blue Venture Fund is an equity-based Venture Capital Fund. It was created to provide capital investments for fast-growing scalable post revenue Tech companies in North America. The sole purpose of the Blue Venture Fund is to grow the North American startup ecosystem. The fund will make capital investments up to $5M per deal for qualified companies.
    investmentCapital: 100000000
    maxInvestmentSize: 5000000
    minimumQualifications:
      - 'The company must be registered in the United States.'
      - 'The company must be in located and operate within the United States.'
      - 'Company ownership of 51% by a founder of United States residency.'
      - 'Must be a for-profit entity.'
      - 'Must have a fully functioning product or service.'
      - 'The company is post-revenue.'
    fundingRequirements:
      - 'The company must have at a minimum of $1.5M in annual revenue'
      - 'The company is at a profitable state'
      - 'Have a management team.'
      - 'Have a complete Advisory board.'
      - 'Pass our Due-Diligence Process.'
    hero: /assets/images/covers/blueventure.jpg
    icon: /assets/images/icons/fund-blueventure-gray.svg
    contentImage: /assets/images/funds/blueventure.jpg
    bullet: /assets/images/icons/bullet-blue.svg
  - name: Great Lakes Angels Fund
    color: yellow
    market: Angel Fund, Pre-Seed Capital
    intro: Great Lakes Angels Fund is an early stage equity-based venture capital fund that was created to seed and grow early stage tech-based companies. It is our highly attractive hybrid investment model. The fund will match the founder(s) capital investment of up to $150K in mix resources per deal for qualified startups. City Side will provide a Full-Stack development team, Seasoned Go-To-Market management team, Board of Directors, Coaching and Mentoring, and Startup Capital to the companies.
    investmentCapital: 10000000
    maxInvestmentSize: 150000
    minimumQualifications:
      - 'The company must be a tech-based company.'
      - 'The company must have a viable business use case.'
      - 'Provide a solid and fully developed business & execution plan.'
      - 'Must be a for-profit entity.'
      - 'Must have a fully developed POC and be Development-Ready.'
    fundingRequirements:
      - 'The company must be registered within the US.'
      - 'Have a management team.'
      - 'Have an Advisory board.'
      - 'Pass our Due-Diligence Process.'
    hero: /assets/images/covers/greatlakes.jpg
    icon: /assets/images/icons/fund-greatlakes-gray.svg
    contentImage: /assets/images/funds/greatlakes.jpg
    bullet: /assets/images/icons/bullet-yellow.svg
  - name: City[X]
    color: black
    market: Private Equity Fund, Growth Capital
    intro: City[X] is a Michigan-based Private Equity Fund that was established to invest in fast growing, scalable, and post-revenue tech companies located in the US and North America. City[X] Fund is an equity-based Private Equity Fund. It was created to provide capital investments for fast-growing scalable post revenue Tech companies in North America. The sole purpose of City[X] Fund is to grow the North American Startup ecosystem. The fund will make capital investments up to $10M per deal for qualified companies.
    investmentCapital: 120000000
    maxInvestmentSize: 10000000
    minimumQualifications:
      - 'The company must be registered in the United States.'
      - 'The company must be in located and operate within the United States.'
      - 'Company ownership of 51% by a founder of United States residency.'
      - 'Must be a for-profit entity.'
      - 'Must have a fully functioning product or service.'
      - 'The company is post-revenue.'
    fundingRequirements:
      - 'The company must have at least $4.5M in annual revenue.'
      - 'The company is at a profitable state.'
      - 'Have a management team.'
      - 'Have a complete Advisory board.'
      - 'Pass our Due-Diligence Process.'
    hero: /assets/images/covers/cityx.jpg
    icon: /assets/images/icons/fund-cityx-gray.svg
    contentImage: /assets/images/funds/cityx.jpg
    bullet: /assets/images/icons/bullet-dark-gray.svg
  - name: Venture248
    color: red
    market: Venture Capital Fund, Seed Capital
    intro: Venture (248) is an equity-based Venture Capital Fund that was created to fund and grow second stage, Michigan-based technology companies. Its sole purpose is to help grow the Michigan tech startup ecosystem. Venture (248) is an equity-based Venture Capital Fund that was created to fund and grow Second Stage Michigan Tech companies. Its sole purpose is to grow the Michigan Tech Startup Ecosystem. The fund provides equity-based capital investment of up to $500K per deal for qualified startups.
    investmentCapital: 20000000
    maxInvestmentSize: 500000
    minimumQualifications:
      - 'The company must be a tech-based company.'
      - 'The company must have a viable business use case.'
      - 'Provide a solid and fully developed business & execution plan.'
      - 'Must be a for-profit entity.'
      - 'Must have a fully developed POC and be Development-Ready.'
    fundingRequirements:
      - 'The company must be registered in the US and also be located in Michigan (or plan to relocate to Michigan?).'
      - 'Have a management team.'
      - 'Have an Advisory board.'
      - 'Pass our Due-Diligence Process.'
    hero: /assets/images/covers/venture248.jpg
    icon: /assets/images/icons/fund-venture248-gray.svg
    contentImage: /assets/images/funds/venture248.jpg
    bullet: /assets/images/icons/bullet-red.svg